# Default values for kube-opex-analytics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

envs:
  KOA_DB_LOCATION: /data/db
  KOA_K8S_API_ENDPOINT: https://kubernetes.default
  KOA_K8S_API_VERIFY_SSL: false
  KOA_COST_MODEL: CUMULATIVE_RATIO
  KOA_BILLING_HOURLY_RATE: 0.0
  KOA_BILLING_CURRENCY_SYMBOL: $

dataVolume:
  persist: true
  capacity: 4Gi
  storageClass: ebs-sc

prometheusOperator:
  enabled: false
  labels:

securityContext:
  enabled: true
  uid: 4583
  gid: 4583

replicaCount: 1

image:
  repository: rchakode/kube-opex-analytics
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

metadata:
  labels:
    app: kube-opex-analytics

service:
  type: ClusterIP
  port: 80
  targetPort: 5483

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: eks-tyc-ingress-nginx
    cert-manager.io/cluster-issuer: cert-manager-infraapps
  labels: {}
  hosts:
    - host: kube-opex-analytics.54.73.79.60.sslip.io
      paths:
        - "/"
# uncomment the following lines and ajust the values to enable TLS
  tls:
  - secretName: kube-opex-analytics-tls
    hosts:
      - kube-opex-analytics.54.73.79.60.sslip.io
#


# priorityClassName: default

resources: {}
# No resource requests not limits is specified by default.
# We leave this as a conscious choice for the user, as this increases chances charts run
# on environments with little resources, such as Minikube.
# If you do want to specify resources, uncomment the following lines, adjust them as necessary,
# and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 256m
  #   memory: 512Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}


tolerations:
  - key: "spotInstance"
    operator: "Equal"
    value: "true"
    effect: "PreferNoSchedule"
  - key: "infra-apps"
    operator: "Equal"
    value: "true"
    effect: "NoExecute"
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 120
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 120

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: lifecycle
          operator: In
          values:
          - OnDemand
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: intent
          operator: In
          values:
          - apps
          - control-apps
